import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { Scheme } from "./schema.ts";
import { catppuccin } from "./schemes/catppuccin.ts";
import { tokyonight } from "./schemes/tokyonight.ts";
import { dracula } from "./schemes/dracula.ts";
import { gruvbox } from "./schemes/gruvbox.ts";
import { nord } from "./schemes/nord.ts";

const schemes: Scheme[] = [catppuccin, tokyonight, dracula, gruvbox, nord];
const defaultScheme = catppuccin;

const TOKEN_MAP: Record<string, keyof Scheme> = {
  "--background": "background",
  "--foreground": "foreground",
  "--card": "card",
  "--card-foreground": "cardForeground",
  "--popover": "popover",
  "--popover-foreground": "popoverForeground",
  "--primary": "primary",
  "--primary-foreground": "primaryForeground",
  "--secondary": "secondary",
  "--secondary-foreground": "secondaryForeground",
  "--muted": "muted",
  "--muted-foreground": "mutedForeground",
  "--accent": "accent",
  "--accent-foreground": "accentForeground",
  "--destructive": "destructive",
  "--destructive-foreground": "destructiveForeground",
  "--border": "border",
  "--input": "input",
  "--ring": "ring",
  "--radius": "radius",
  "--crust": "crust",
  "--base": "base",
  "--surface-0": "surface0",
  "--surface-1": "surface1",
  "--color-success": "colorSuccess",
  "--color-warning": "colorWarning",
  "--color-error": "colorError",
  "--color-info": "colorInfo",
  "--duration-fast": "durationFast",
  "--duration-normal": "durationNormal",
  "--ease-default": "easeDefault",
};

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

function luminance(hex: string): number {
  const [r, g, b] = hexToRgb(hex).map((c) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrastRatio(hex1: string, hex2: string): number {
  const l1 = luminance(hex1);
  const l2 = luminance(hex2);
  const lighter = Math.max(l1, l2);
  const darker = Math.min(l1, l2);
  return (lighter + 0.05) / (darker + 0.05);
}

function checkContrast(scheme: Scheme): void {
  const pairs: [string, keyof Scheme, keyof Scheme, number][] = [
    ["foreground on background", "foreground", "background", 4.5],
    ["foreground on card", "cardForeground", "card", 4.5],
    ["foreground on popover", "popoverForeground", "popover", 4.5],
    ["primary-fg on primary", "primaryForeground", "primary", 4.5],
    ["secondary-fg on secondary", "secondaryForeground", "secondary", 4.5],
    ["muted-fg on background", "mutedForeground", "background", 3],
    ["destructive-fg on destructive", "destructiveForeground", "destructive", 3],
  ];

  for (const [label, fgKey, bgKey, required] of pairs) {
    const fg = scheme[fgKey] as string;
    const bg = scheme[bgKey] as string;
    if (!fg.startsWith("#") || !bg.startsWith("#")) continue;
    const ratio = contrastRatio(fg, bg);
    if (ratio < required) {
      console.warn(
        `  ⚠ ${scheme.name}: ${label} — ratio ${ratio.toFixed(2)}:1 (need ${required}:1)`,
      );
    }
  }
}

function generateSchemeBlock(scheme: Scheme): string {
  const lines: string[] = [];
  for (const [cssVar, key] of Object.entries(TOKEN_MAP)) {
    lines.push(`  ${cssVar}: ${scheme[key]};`);
  }
  return lines.join("\n");
}

function generate(): string {
  const parts: string[] = ["/* Auto-generated by src/tokens/generate.ts — do not edit */", ""];

  // :root gets the default scheme
  parts.push(`:root,\n.${defaultScheme.className} {\n${generateSchemeBlock(defaultScheme)}\n}`);

  // Other schemes
  for (const scheme of schemes) {
    if (scheme.className === defaultScheme.className) continue;
    parts.push(`\n.${scheme.className} {\n${generateSchemeBlock(scheme)}\n}`);
  }

  // Reduced motion override
  parts.push(
    `\n@media (prefers-reduced-motion: reduce) {\n  :root {\n    --duration-fast: 0ms;\n    --duration-normal: 0ms;\n  }\n}`,
  );

  return parts.join("\n") + "\n";
}

// Run
console.log("Generating theme CSS...");
for (const scheme of schemes) {
  console.log(`  ✓ ${scheme.name} (${scheme.className})`);
  checkContrast(scheme);
}

const css = generate();
const outPath = resolve(dirname(fileURLToPath(import.meta.url)), "generated-themes.css");
writeFileSync(outPath, css, "utf-8");
console.log(`\nWritten to ${outPath}`);
